### PR TITLE
fix: update channel join payload for successful reconnect

### PR DESCRIPTION
**Pull request by w3b6x9**
## What kind of change does this PR introduce?

Bug fix

## What is the current behavior?

Channel (subscription) is created with `user_token` with an expiration that never gets updated with `setAuth` (never refreshed). No successful reconnection after `user_token` has expired even though `supabase-js` is calling `setAuth` with refreshed token.

## What is the new behavior?

`setAuth` will update each channel's join payload with the latest `user_token`.

## Additional context

Related issue: https://github.com/supabase/realtime-js/issues/123

### CODE REVIEW

**Review by kiwicopple — APPROVED** [review]

**Comment by acupofjose** [comment]
Just to confirm - we are using `user_token` and `access_token` for the same token: `user_token` in the initial join push (and subsequent rejoins) and `access_token` on an already joined channel?

**Comment by w3b6x9** [comment]
@acupofjose that’s correct! We’ll consolidate the naming of the token in the future so it’s uniform. Sorry for the confusion!

**Comment by kamyker** [comment]
I have to say it's a bit weird that for every channel there is additional push calls on every heartbeat. That doesn't sound very scalable and multiplexed.

**Comment by w3b6x9** [comment]
> I have to say it's a bit weird that for every channel there is additional push call on every heartbeat. That doesn't sound very scalable and multiplexed.

@kamyker do you mean the additional push as a result of invoking `setAuth`?

**Comment by kamyker** [comment]
> > I have to say it's a bit weird that for every channel there is additional push call on every heartbeat. That doesn't sound very scalable and multiplexed.
> 
> @kamyker do you mean the additional push as a result of invoking `setAuth`?

Yes

**Pull request merged**
