### PR TITLE
fix: Handle properly jwt tokens

### PR DESCRIPTION
**Pull request by filipecabaco**
## What kind of change does this PR introduce?

Handle properly jwt tokens as currently we were using only the apikey and that is not enough for scenarios with RLS policies.

### CODE REVIEW

**Review by chasers — APPROVED** [review]

**Comment by w3b6x9** [comment]
@filipecabaco what's the distinction between the tokens? How is Realtime server gonna use either?

**Comment by chasers** [comment]
Oh also need to do this in the Broadcast POST!

**Comment by chasers** [comment]
API Gateway requires anon or service role for the apikey.

**Comment by filipecabaco** [comment]
What @chasers said. We need to emulate the following request:
```
const response = await fetch(channelUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${session?.access_token!}`,
        apikey: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      },
      body: JSON.stringify({ name }),
    });
```

**Comment by filipecabaco** [comment]
added the same logic to HTTP Broadcast push

**Pull request merged**
